[workspace]
resolver = "2"

members = [
    "quadratic-connection",
    "quadratic-core",
    "quadratic-files",
    "quadratic-multiplayer",
    "quadratic-rust-client",
    "quadratic-rust-shared",
]

[workspace.package]
authors = ["Quadratic"]
edition = "2021"
description = "Infinite data grid with Python, JavaScript, and SQL built-in"
repository = "https://github.com/quadratichq/quadratic"
license-file = "LICENSE"
version = "1.0.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
