[workspace]
resolver = "2"

members = [
    "quadratic-connection",
    "quadratic-core",
    "quadratic-files",
    "quadratic-multiplayer",
    "quadratic-rust-client",
    "quadratic-rust-shared",
    "quadratic-rust-shared/proc_macros/function-timer",
]


[workspace.package]
authors = ["Quadratic"]
edition = "2024"
description = "Infinite data grid with Python, JavaScript, and SQL built-in"
repository = "https://github.com/quadratichq/quadratic"
license-file = "LICENSE"
version = "0.6.7"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
