version: "3.8"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    volumes:
      - ./docker/redis/data:/data
    profiles:
      - base
      - all

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    profiles:
      - base
      - all

  localstack:
    extends:
      file: docker-compose.base.yml
      service: localstack
    volumes:
      - "./docker/localstack/scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh" # ready hook
      - "./docker/localstack/data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    profiles:
      - base
      - all

  # nginx:
  #   restart: always
  #   image: nginx:1-alpine
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 3000:80
  #   volumes:
  #     - ./docker/static/html:/usr/share/nginx/html
  #     - ./docker/static/conf/:/etc/nginx/conf.d/:ro
  #     - ./docker/static/certs:/etc/nginx/ssl
  #     # - ./docker/static/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - quadratic-api
  #   # networks:
  #   #   - host

  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   env_file:
  #     - quadratic-client/.env.local
  #     - quadratic-client/.env.docker
  #   # override env vars here
  #   environment:
  #     DOMAINS: >
  #       quadratic.lvh.me,
  #       quadratic-api.lvh.me -> http://quadratic-api:8000,
  #       quadratic-multiplayer.lvh.me -> http://quadratic-multiplayer:3001/ws,
  #       quadratic-localstack.lvh.me -> http://localstack:4566
  #     STAGE: "local" # Use 'production' to use a LetsEncrypt signed SSL cert
  #     FORCE_RENEW: "false"
  #     WEBSOCKET: "true"

  #     VITE_QUADRATIC_API_URL: http://0.0.0.0:8000
  #     VITE_QUADRATIC_MULTIPLAYER_URL: ws://0.0.0.0:3001
  #     VITE_QUADRATIC_CONNECTION_URL: http://0.0.0.0:3003
  #   depends_on:
  #     # - quadratic-client
  #     - quadratic-api
  #   volumes:
  #     - ./docker/https-portal/data:/var/lib/https-portal
  #     - ./docker/https-portal/vhosts:/var/www/vhosts
  #     - ./docker/https-portal/quadratic.lvh.me.conf.erb:/var/lib/nginx-conf/quadratic.lvh.me.conf.erb:ro
  #     - ./docker/https-portal/quadratic.lvh.me.ssl.conf.erb:/var/lib/nginx-conf/quadratic.lvh.me.ssl.conf.erb:ro

  quadratic-client:
    build:
      context: .
      dockerfile: client.Dockerfile
    env_file:
      - quadratic-client/.env.local
      - quadratic-client/.env.docker
    # override env vars here
    environment:
      VITE_QUADRATIC_API_URL: http://localhost:8000
      VITE_QUADRATIC_MULTIPLAYER_URL: ws://localhost:3001
      VITE_QUADRATIC_CONNECTION_URL: http://0.0.0.0:3003
    restart: "always"
    ports:
      # - "3000:3000"
      - 80:80
      - 443:443
      - 3000:80
    # command: "npm run start:production --workspace=quadratic-client"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - client
      - frontend
      - all
    volumes:
      # - ./docker/static/html:/usr/share/nginx/html
      - ./docker/static/conf/:/etc/nginx/conf.d/:ro
      - ./docker/static/certs:/etc/nginx/ssl
      # - ./docker/static/default.conf:/etc/nginx/conf.d/default.conf
    # networks:
    #   - host

  quadratic-api:
    build:
      context: .
      dockerfile: quadratic-api/Dockerfile
    env_file:
      - quadratic-api/.env
      - quadratic-api/.env.docker
    # override env vars here
    environment:
      AWS_S3_ENDPOINT: https://localhost/localstack
    restart: "always"
    ports:
      - "8000:8000"
    command: "npm run start:prod --workspace=quadratic-api"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - api
      - frontend
      - all

  quadratic-multiplayer:
    build:
      context: .
      dockerfile: quadratic-multiplayer/Dockerfile
      args:
        - binary=quadratic-multiplayer
    env_file:
      - quadratic-multiplayer/.env.docker
    # override env vars here
    environment:
      QUADRATIC_API_URI: http://host.docker.internal:8000
      RUST_LOG: info
    restart: "always"
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      quadratic-api:
        condition: service_started
    profiles:
      - backend
      - quadratic-multiplayer
      - all
    networks:
      - host

  quadratic-files:
    build:
      context: .
      dockerfile: quadratic-files/Dockerfile
      args:
        - binary=quadratic-files
    env_file:
      - quadratic-files/.env.docker
    # override env vars here
    environment:
      QUADRATIC_API_URI: http://host.docker.internal:8000
      RUST_LOG: info
    restart: "always"
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      quadratic-api:
        condition: service_started
    profiles:
      - backend
      - quadratic-files
      - all
    networks:
      - host

  quadratic-connection:
    build:
      context: .
      dockerfile: quadratic-connection/Dockerfile
      args:
        - binary=quadratic-connection
    env_file:
      - quadratic-connection/.env.docker
    # override env vars here
    environment:
      QUADRATIC_API_URI: http://host.docker.internal:8000
      RUST_LOG: info
    restart: "always"
    ports:
      - "3003:3003"
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   quadratic-api:
    #     condition: service_started
    profiles:
      - backend
      - quadratic-connection
      - all

  # Databases to be used for testing by the connection service

  postgres-connection:
    image: postgres:15
    restart: always
    container_name: postgres-connection
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres-connection
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres-connection"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/postgres-connection/data:/var/lib/postgresql/data
      - ./docker/postgres-connection/scripts:/docker-entrypoint-initdb.d
    profiles:
      - additional-databases
      - quadratic-connection
      - quadratic-connection-test
      - all

  mysql-connection:
    image: mysql:8
    restart: always
    container_name: mysql-connection
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql-connection
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/mysql-connection/data:/var/lib/mysql
      - ./docker/mysql-connection/scripts:/docker-entrypoint-initdb.d/
    profiles:
      - additional-databases
      - quadratic-connection
      - quadratic-connection-test
      - all

volumes:
  docker:
    name: docker

networks:
  host:
