name: Deploy to AWS CloudFormation - Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-${{ github.event.pull_request.number }}-deploy-cloudformation

jobs:
  deploy_cloudformation:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      
    runs-on: blacksmith-2vcpu-ubuntu-2204

    env:
      STACK_NAME: pr-${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate Build Metadata
        id: build-metadata
        run: |
          echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        id: deploy-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.STACK_NAME }}
          template: infra/aws-cloudformation/preview-deployment-template.yml
          parameter-overrides: >-
            LicenseKey=5a32bd8a-409e-4733-8846-1868c568a813,
            ImageTag=pr-${{ github.event.pull_request.number }},
            GitSHA=${{ steps.build-metadata.outputs.GIT_SHA_SHORT }}
          capabilities: CAPABILITY_IAM
          no-fail-on-empty-changeset: "1"
          disable-rollback: false
          termination-protection: false

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: preview-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Preview Deployment'

      - name: Create or update comment
        if: steps.deploy-stack.outputs.DnsRecord != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.preview-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Preview Deployment
            Preview URL: https://${{ steps.deploy-stack.outputs.DnsRecord }}
          edit-mode: replace
          
