name: Build and Publish Images to ECR

on:
  push:
    branches:
      - self-hosting-setup 

concurrency:
  group: production-publish-images

jobs:
  publish_images:
    runs-on: ubuntu-latest-8-cores
    strategy:
      matrix:
        service: [multiplayer, files, connection, client, api]
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPMENT }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create Public ECR Repository if not exists
      id: create-ecr
      run: |
        REPO_INFO=$(aws ecr-public describe-repositories --repository-names quadratic-${{ matrix.service }}-production || \
        aws ecr-public create-repository --repository-name quadratic-${{ matrix.service }}-production)
        ECR_URL=$(echo $REPO_INFO | jq -r '.repositories[0].repositoryUri')
        echo "ECR_URL=$ECR_URL" >> $GITHUB_OUTPUT

    - name: Build, Tag, and Push Image to Amazon ECR Public
      env:
        ECR_URL: ${{ steps.create-ecr.outputs.ECR_URL }}
        IMAGE_TAG: 0.1.0
      run: |
        docker build -t $ECR_URL:$IMAGE_TAG -f quadratic-${{ matrix.service }}/Dockerfile .
        docker push $ECR_URL:$IMAGE_TAG