name: QA

on:
  pull_request:
    branches:
      # - main
      - qa
    types: [opened, synchronize, reopened]

# Use runs on `ubuntu-latest-8-cores`. All of our self hosted runners use this tag.
# Our runners pick up jobs first, and if all our runners are being used or are down
# it will automatically back up to using GitHub hosted runners.

# Require previous builds and deployments to finish before starting a new one
# Not sure how Pulumi would handle being terminated when changing a stack.
concurrency:
  group: qa

env:
  AMPLIFY_APP_ID: d3dmk4wdzzskoq
  S3_BUCKET_NAME: quadratic-development-amplify

jobs:
  build_client:
    name: Build Client
    runs-on: blacksmith-4vcpu-ubuntu-2204
    # if: github.head_ref == 'qa' && github.base_ref == 'main'
    timeout-minutes: 30
    outputs:
      s3-dir: ${{ steps.upload-to-s3.outputs.s3-dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Cache Docker layers
        uses: useblacksmith/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-client-${{ hashFiles('quadratic-client/Dockerfile.amplify') }}-qa-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-client-${{ hashFiles('quadratic-client/Dockerfile.amplify') }}-qa-
            ${{ runner.os }}-buildx-client-${{ hashFiles('quadratic-client/Dockerfile.amplify') }}-

      - name: Build using Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: quadratic-client/Dockerfile.amplify
          push: false
          load: true
          tags: quadratic-client:local
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          outputs: type=docker

      - name: Copy build from container to host
        run: |
          # Create a temporary container from the image
          CONTAINER_ID=$(docker create quadratic-client:local)

          # Create a temporary directory to hold the build
          mkdir -p /tmp/quadratic-client

          # Copy the build files from the container using the correct path
          docker cp $CONTAINER_ID:/usr/share/nginx/html/. /tmp/quadratic-client/

          # Clean up the temporary container
          docker rm $CONTAINER_ID

      - name: Upload to S3
        id: upload-to-s3
        run: |
          COMMIT_HASH="${{ github.event.pull_request.head.sha }}"

          # S3 build directory
          S3_DIR="s3://${S3_BUCKET_NAME}/quadratic-client-${COMMIT_HASH}/"

          # Upload entire build directory to S3 with no caching for Amplify
          aws s3 sync /tmp/quadratic-client/ $S3_DIR --delete

          echo "s3-dir=$S3_DIR" >> $GITHUB_OUTPUT

  build_images:
    name: Build Images
    runs-on: ${{ matrix.runner }}
    if: github.head_ref == 'qa' && github.base_ref == 'main'
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - service: api
            runner: blacksmith-2vcpu-ubuntu-2204
          - service: connection
            runner: blacksmith-4vcpu-ubuntu-2204
          - service: files
            runner: blacksmith-4vcpu-ubuntu-2204
          - service: multiplayer
            runner: blacksmith-4vcpu-ubuntu-2204
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Build Metadata
        id: build-metadata
        run: |
          echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(echo "${{ github.head_ref }}" | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Define repository name
        id: repo-name
        run: |
          echo "REPO_NAME=quadratic-${{ matrix.service }}-development" >> $GITHUB_OUTPUT

      - name: Create Private ECR Repository
        id: create-ecr
        env:
          REPO_NAME: ${{ steps.repo-name.outputs.REPO_NAME }}
        run: |
          # Try to describe the repository first
          if ! aws ecr describe-repositories --repository-names $REPO_NAME 2>/dev/null; then
            # Repository doesn't exist, create it
            aws ecr create-repository --repository-name $REPO_NAME || true
          fi

          # Get the repository URI either way
          REPO_INFO=$(aws ecr describe-repositories --repository-names $REPO_NAME)
          ECR_URL=$(echo $REPO_INFO | jq -r '.repositories[0].repositoryUri')
          echo "ECR_URL=$ECR_URL" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Cache Docker layers
        uses: useblacksmith/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ hashFiles(format('quadratic-{0}/Dockerfile', matrix.service)) }}-qa-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-${{ hashFiles(format('quadratic-{0}/Dockerfile', matrix.service)) }}-qa
            ${{ runner.os }}-buildx-${{ matrix.service }}-${{ hashFiles(format('quadratic-{0}/Dockerfile', matrix.service)) }}-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: quadratic-${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.create-ecr.outputs.ECR_URL }}:pr-qa-github-actions
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          secrets: |
            "VITE_DEBUG=${{ secrets.VITE_DEBUG_DEVELOPMENT }}"
            "VITE_QUADRATIC_API_URL=${{ secrets.VITE_QUADRATIC_API_URL_DEVELOPMENT }}"
            "VITE_QUADRATIC_MULTIPLAYER_URL=${{ secrets.VITE_QUADRATIC_MULTIPLAYER_URL_DEVELOPMENT }}"
            "VITE_QUADRATIC_CONNECTION_URL=${{ secrets.VITE_QUADRATIC_CONNECTION_URL_DEVELOPMENT }}"
            "VITE_STORAGE_TYPE=${{ secrets.VITE_STORAGE_TYPE_DEVELOPMENT }}"
            "VITE_AUTH_TYPE=${{ secrets.VITE_AUTH_TYPE_DEVELOPMENT }}"
            "VITE_AUTH0_ISSUER=${{ secrets.VITE_AUTH0_ISSUER_DEVELOPMENT }}"
            "VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN_DEVELOPMENT }}"
            "VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID_DEVELOPMENT }}"
            "VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE_DEVELOPMENT }}"
            "VITE_ORY_HOST=${{ secrets.VITE_ORY_HOST_DEVELOPMENT }}"
            "VITE_SENTRY_AUTH_TOKEN=${{ secrets.VITE_SENTRY_AUTH_TOKEN_DEVELOPMENT }}"
          build-args: |
            BUILD_TIME=${{ steps.build-metadata.outputs.BUILD_TIME }}
            GIT_SHA_SHORT=${{ steps.build-metadata.outputs.GIT_SHA_SHORT }}
            BRANCH_NAME=${{ steps.build-metadata.outputs.BRANCH_NAME }}
            PR_NUMBER=${{ github.event.pull_request.number }}
          labels: |
            org.opencontainers.image.created=${{ steps.build-metadata.outputs.BUILD_TIME }}
            org.opencontainers.image.revision=${{ github.sha }}

  amplify:
    # needs: [build_client, build_images]
    needs: [build_client]
    name: Deploy Client to Amplify
    runs-on: blacksmith-2vcpu-ubuntu-2204
    # if: github.head_ref == 'qa' && github.base_ref == 'main'
    timeout-minutes: 30
    steps:
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cancel Pending Deployments
        run: |
          # List and cancel any pending jobs with improved error handling
          echo "Checking for pending Amplify jobs..."
          if ! JOBS=$(aws amplify list-jobs \
            --app-id ${{ env.AMPLIFY_APP_ID }} \
            --branch-name ${{ github.head_ref }} \
            --output json); then
            echo "Failed to list Amplify jobs. Continuing anyway..."
          else
            # Count pending/running jobs for better visibility
            PENDING_COUNT=$(echo "$JOBS" | jq -r '.jobSummaries[] | select(.status == "PENDING" or .status == "RUNNING") | .jobId' | wc -l)
            echo "Found $PENDING_COUNT pending or running jobs"
            
            # Cancel jobs with timeout and status reporting
            echo "$JOBS" | jq -r '.jobSummaries[] | select(.status == "PENDING" or .status == "RUNNING") | "\(.jobId) \(.status) \(.jobType)"' | \
            while read -r JOB_ID STATUS TYPE; do
              echo "Cancelling $TYPE job $JOB_ID (status: $STATUS)"
              if aws amplify stop-job \
                --app-id ${{ env.AMPLIFY_APP_ID }} \
                --branch-name ${{ github.head_ref }} \
                --job-id "$JOB_ID"; then
                echo "✓ Successfully cancelled job $JOB_ID"
              else
                echo "⚠️ Failed to cancel job $JOB_ID, but continuing"
              fi
            done
            
            # Verify jobs were stopped - optional check
            echo "Verifying jobs are no longer running..."
            sleep 2
            REMAINING=$(aws amplify list-jobs \
              --app-id ${{ env.AMPLIFY_APP_ID }} \
              --branch-name ${{ github.head_ref }} \
              --output json | jq -r '.jobSummaries[] | select(.status == "PENDING" or .status == "RUNNING") | .jobId' | wc -l)
            echo "$REMAINING jobs still pending or running"
          fi

      - name: Trigger New Deployment
        run: |
          aws amplify start-deployment \
            --app-id ${{ env.AMPLIFY_APP_ID }} \
            --branch-name ${{ github.head_ref }} \
            --source-url ${{ needs.build_client.outputs.s3-dir }} \
            --source-url-type "BUCKET_PREFIX"

  pulumi:
    needs: [build_client, build_images]
    name: Create or Update Pulumi Infrastructure Stack
    runs-on: blacksmith-2vcpu-ubuntu-2204
    if: github.head_ref == 'qa' && github.base_ref == 'main'
    timeout-minutes: 30
    env:
      STACK_NAME: quadratic-qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pulumi/actions@v4

      - name: Update Pulumi Infrastructure
        working-directory: infra
        run: |
          npm ci

          pulumi org set-default quadratic

          if ! pulumi stack ls | grep -q "^$STACK_NAME"; then
            echo "Stack $STACK_NAME does not exist. Initializing..."
            pulumi stack init $STACK_NAME
          else
            echo "Stack $STACK_NAME already exists."
            pulumi stack select $STACK_NAME
          fi

          # Point to the Pulumi ESC Environment
          cat <<EOF | tee Pulumi.$STACK_NAME.yaml
          environment:
            - aws-infra-development
          EOF

          pulumi config set multiplayer-subdomain multiplayer-pr-qa
          pulumi config set files-subdomain files-pr-qa
          pulumi config set connection-subdomain connection-pr-qa
          pulumi config set docker-image-tag pr-qa
          pulumi config set quadratic-api-uri https://quadratic-staging.herokuapp.com
          pulumi config set is-preview true

          pulumi up -y
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPMENT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PR_ID: ${{ github.event.pull_request.number }}
